%% Methods
-define(STATE, <<"_cluster/state">>).
-define(HEALTH, <<"_cluster/health">>).
-define(NODES, <<"_nodes">>).
-define(STATUS, <<"_status">>).
-define(STATS, <<"stats">>).
-define(INDICES_STATS, <<"_stats">>).
-define(SEARCH, <<"_search">>).
-define(REFRESH, <<"_refresh">>).
-define(FLUSH, <<"_flush">>).
-define(OPEN, <<"_open">>).
-define(CLOSE, <<"_close">>).
-define(MGET, <<"_mget">>).
-define(COUNT, <<"_count">>).
-define(QUERY, <<"_query">>).
-define(DELETE_BY_QUERY, <<"_delete_by_query">>).
-define(OPTIMIZE, <<"_optimize">>).
-define(SEGMENTS, <<"_segments">>).
-define(CLEAR_CACHE, <<"_cache/clear">>).
-define(MAPPING, <<"_mapping">>).
-define(ALIASES, <<"_aliases">>).
-define(ALIAS, <<"_alias">>).
-define(UPDATE, <<"_update">>).
-define(BULK, <<"_bulk">>).

% Shortcuts
-define(ALL, <<"_all">>).
